import { Geist, Geist_Mono } from "next/font/google";
import { Playfair_Display, Open_Sans, Meddon } from "next/font/google";
import "./globals.css";
import Footer from "../components/sections/footer";
import MainNav from "../components/mainNav";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-playfair",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-opensans",
});

const meddon = Meddon({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-meddon",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      {/* <div className="grid-overlay"></div> */}
      <body
        className={`${playfair.variable} ${openSans.variable} ${meddon.variable} antialiased`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
