import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/sections/footer";
import MainNav from "../components/mainNav";
import { Lora } from "next/font/google";

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${lora.className} antialiased`}>
        <MainNav />

        <main className="text-lg overflow-x-hidden">
          <div className="">{children}</div>

          <Footer />
        </main>
      </body>
    </html>
  );
}
